stages:
- production
production:
    stage: production
    image: ruby:latest
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=pictures-game --api-key=$HEROKU_API_KEY
    only:
        - master  #branch name to deploy on heroku
